// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: order.proto

package orderclient

import (
	"context"

	"order-rpc/order"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	OrderInfoReq  = order.OrderInfoReq
	OrderInfoResp = order.OrderInfoResp

	Order interface {
		GetOrderInfo(ctx context.Context, in *OrderInfoReq, opts ...grpc.CallOption) (*OrderInfoResp, error)
	}

	defaultOrder struct {
		cli zrpc.Client
	}
)

func NewOrder(cli zrpc.Client) Order {
	return &defaultOrder{
		cli: cli,
	}
}

func (m *defaultOrder) GetOrderInfo(ctx context.Context, in *OrderInfoReq, opts ...grpc.CallOption) (*OrderInfoResp, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.GetOrderInfo(ctx, in, opts...)
}
