// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: order.proto

package server

import (
	"context"

	"order-rpc/internal/logic"
	"order-rpc/internal/svc"
	"order-rpc/order"
)

type OrderServer struct {
	svcCtx *svc.ServiceContext
	order.UnimplementedOrderServer
}

func NewOrderServer(svcCtx *svc.ServiceContext) *OrderServer {
	return &OrderServer{
		svcCtx: svcCtx,
	}
}

func (s *OrderServer) GetOrderInfo(ctx context.Context, in *order.OrderInfoReq) (*order.OrderInfoResp, error) {
	l := logic.NewGetOrderInfoLogic(ctx, s.svcCtx)
	return l.GetOrderInfo(in)
}
