// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package handler

import (
	"net/http"

	"user-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/order/:id",
				Handler: OrderInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user",
				Handler: CreateUserHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/:id",
				Handler: UserInfoHandler(serverCtx),
			},
		},
	)
}
