// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type CreateUserReq struct {
	Name string `json:"name"`
}

type CreateUserResp struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

type OrderInfoReq struct {
	Id string `path:"id"`
}

type OrderInfoResp struct {
	Id      string `json:"id"`
	Product string `json:"product"`
	Amount  int32  `json:"amount"`
}

type UserInfoReq struct {
	Id string `path:"id"`
}

type UserInfoResp struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}
